### ISSUE TITLE
base64PublicKey

### ISSUE THREAD

**Issue by chiragpurohit71085** [LiteKite/Android-InAppBilling#1]
Hi 

where I need to put base64PublicKey? to follow

Copy the application's public key (a base-64 string). You can find this in the "Services & APIs" section under "Licensing & In-App Billing".

IN THE CODE

Open BillingManager.java, find the declaration of BASE_64_ENCODED_PUBLIC_KEY constant and replace its value with the public key you retrieved in Step 2.

**Comment by svignesh93** [comment]
Hi,

There's no need to include your BASE_64_ENCODED_PUBLIC_KEY anywhere inside your project. Simply use this new BillingClient Library 'com.android.billingclient:billing:1.0' and make sure you use same Application ID (package name) that's been used in the play store and android project as well.

**Comment by chiragpurohit71085** [comment]
okay thanks
