### ISSUE TITLE
NOVICE HELP PLEASE ? I need it urgently !

### ISSUE THREAD

**Issue by SirGatsby** [LiteKite/Android-InAppBilling#11]
Hy, i have setup it correctly now , but now i don't know how to consume it, i mean the apple in "View my purchase" how i consume the apple when i click on it ? i want something like to consume it to open an new activity where i put my code, how i can make it work ? And some for unlimited popcorn, how i can make it to consume it ? Can i have some detailed code  please ?

**Comment by svignesh93** [comment]
Closing this issue as this was not related to any issues with the code base. I'd request to use "billing" package where "BillingManager" java class does all the work, but you may require to configure your app's Google Play Account SKU constants to make purchases work.
