### ISSUE TITLE
Error while retrieving information from server [DF-AA-20]

### ISSUE THREAD

**Issue by kashifansari786** [LiteKite/Android-InAppBilling#2]
Every time i hit button on home page it shown me this error and when i search in internet it tell me publish ur app in alpha testing and i published app in alpha testing and again this error is happen i dont know why and some say replace your base64 string key in code but i didt see any where any key which is base64 string please help me to resolve this.

**Comment by svignesh93** [comment]
Hi,

There's no need to include your BASE_64_ENCODED_PUBLIC_KEY anywhere inside your project. Simply use this new BillingClient Library 'com.android.billingclient:billing:1.0' and make sure you use same Application ID (package name) that's been used in the play store and android project as well.

![6_billing_error](https://user-images.githubusercontent.com/13173067/46034460-4d9b4080-c11e-11e8-9170-7df963c1b6c3.png)

If you are experiencing like the above picture, please ensure that you have updated your APK in BETA Channel and make sure you are using same package name in Play Store and and in your project as well.
