### ISSUE TITLE
Subscriptions and inapp purchases shows as $0

### ISSUE THREAD

**Issue by sweatbar** [LiteKite/Android-InAppBilling#5]
Hi,
I Signed and uploaded the apk to the Alpha release and created the sku's accordingly. Even the package name is same on both play store and on android studio(renamed package in Gradle).

Still I'm getting $0 and if i click on Buy now it will show as "Something went wrong on our end"

How to fix this?

Thanks

**Comment by svignesh93** [comment]
Hi,

Please update your APK on the beta channel and also ensure that the package name is same as the app module that you defined in your Gradle File.
