### ISSUE TITLE
 Update for 'com.android.billingclient: billing: 2.0.3'?

### ISSUE THREAD

**Issue by Moh09** [LiteKite/Android-InAppBilling#6]
Thank you very much for this sample!
Is there a chance that the app will be updated for 'com.android.billingclient: billing: 2.0.3'?

**Comment by svignesh93** [comment]
Hi,

I've been working on migrating android support libraries to AndroidX. I'll also update the billing library in the gradle following that. I'll give an update this week.

**Comment by svignesh93** [comment]
Hi,

I just updated the code to AndroidX and Billing Library 2.0.3. Please update in a new thread if there is any issues.
